version: 2.1

executors:
  default:
    working_directory: ~
    docker:
      - image: circleci/node:12.14.1

commands:
  restore_dependencies_cache:
    steps:
      - restore_cache:
          key: yarn-v1-packages-{{ checksum "yarn.lock" }}
  save_dependencies_cache:
    steps:
      - save_cache:
          key: yarn-v1-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  install:
    executor:
      name: default
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - checkout
      - restore_dependencies_cache
      - run: yarn install --frozen-lockfile
      - save_dependencies_cache
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_dependencies_cache
      - run: npm run build
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_dependencies_cache
      - run: npm run lint
  license-check:
    executor:
      name: default
    steps:
      - checkout
      - restore_dependencies_cache
      - run: fossa analyze
      - run: fossa test

workflows:
  main:
    jobs:
      - install
      - build:
          requires:
            - install
      - license-check:
          requires:
            - build
      - test:
          requires:
            - install
